const initialState = {
  toggle: false,
  // Mock data for shows
  shows: [
    {
      name: "Show 1",
      id: 1,
      seatingArrangement: [
        {
          category: "Platinum",
          price: 320,
          row: [
            { name: "A1", prize: 320 },
            { name: "A2", prize: 320 },
            { name: "A3", prize: 320 },
            { name: "A4", prize: 320 },
            { name: "A5", prize: 320 },
            { name: "A6", prize: 320 },
            { name: "A7", prize: 320 },
            { name: "A8", prize: 320 },
            { name: "A9", prize: 320, class: "disappear" },
            { name: "A10", prize: 320, class: "disappear" },
          ],
        },
        {
          category: "Gold",
          price: 300,
          row: [
            { name: "B1", prize: 300, class: "disappear" },
            { name: "B2", prize: 300 },
            { name: "B3", prize: 300 },
            { name: "B4", prize: 300 },
            { name: "B5", prize: 300 },
            { name: "B6", prize: 300 },
            { name: "B7", prize: 300 },
            { name: "B8", prize: 300, class: "disappear" },
            { name: "B9", prize: 300, class: "disappear" },
            { name: "B10", prize: 300, class: "disappear" },
          ],
        },
        {
          category: "Silver",
          price: 280,
          row: [
            { name: "C1", prize: 280 },
            { name: "C2", prize: 280 },
            { name: "C3", prize: 280 },
            { name: "C4", prize: 280 },
            { name: "C5", prize: 280 },
            { name: "C6", prize: 280 },
            { name: "C7", prize: 280 },
            { name: "C8", prize: 280 },
            { name: "C9", prize: 280, class: "disappear" },
            { name: "C10", prize: 280, class: "disappear" },
          ],
        },
      ],
    },
    {
      name: "Show 2",
      id: 2,
      seatingArrangement: [
        {
          category: "Platinum",
          price: 320,
          row: [
            { name: "A1", prize: 320 },
            { name: "A2", prize: 320 },
            { name: "A3", prize: 320 },
            { name: "A4", prize: 320 },
            { name: "A5", prize: 320 },
            { name: "A6", prize: 320 },
            { name: "A7", prize: 320 },
            { name: "A8", prize: 320, class: "disappear" },
            { name: "A9", prize: 320, class: "disappear" },
            { name: "A10", prize: 320, class: "disappear" },
          ],
        },
        {
          category: "Gold",
          price: 300,
          row: [
            { name: "B1", prize: 300 },
            { name: "B2", prize: 300 },
            { name: "B3", prize: 300 },
            { name: "B4", prize: 300 },
            { name: "B5", prize: 300 },
            { name: "B6", prize: 300 },
            { name: "B7", prize: 300 },
            { name: "B8", prize: 300 },
            { name: "B9", prize: 300, class: "disappear" },
            { name: "B10", prize: 300, class: "disappear" },
          ],
        },
        {
          category: "Silver",
          price: 280,
          row: [
            { name: "C1", prize: 280 },
            { name: "C2", prize: 280 },
            { name: "C3", prize: 280 },
            { name: "C4", prize: 280 },
            { name: "C5", prize: 280 },
            { name: "C6", prize: 280 },
            { name: "C7", prize: 280 },
            { name: "C8", prize: 280 },
            { name: "C9", prize: 280 },
            { name: "C10", prize: 280, class: "disappear" },
          ],
        },
      ],
    },
    {
      name: "Show 3",
      id: 3,
      seatingArrangement: [
        {
          category: "Platinum",
          price: 320,
          row: [
            { name: "A1", prize: 320 },
            { name: "A2", prize: 320 },
            { name: "A3", prize: 320 },
            { name: "A4", prize: 320 },
            { name: "A5", prize: 320 },
            { name: "A6", prize: 320 },
            { name: "A7", prize: 320 },
            { name: "A8", prize: 320 },
            { name: "A9", prize: 320, class: "disappear" },
            { name: "A10", prize: 320, class: "disappear" },
          ],
        },
        {
          category: "Gold",
          price: 300,
          row: [
            { name: "B1", prize: 300 },
            { name: "B2", prize: 300 },
            { name: "B3", prize: 300 },
            { name: "B4", prize: 300 },
            { name: "B5", prize: 300 },
            { name: "B6", prize: 300 },
            { name: "B7", prize: 300 },
            { name: "B8", prize: 300, class: "disappear" },
            { name: "B9", prize: 300, class: "disappear" },
            { name: "B10", prize: 300, class: "disappear" },
          ],
        },
        {
          category: "Silver",
          price: 280,
          row: [
            { name: "C1", prize: 280, class: "disappear" },
            { name: "C2", prize: 280, class: "disappear" },
            { name: "C3", prize: 280 },
            { name: "C4", prize: 280 },
            { name: "C5", prize: 280 },
            { name: "C6", prize: 280 },
            { name: "C7", prize: 280 },
            { name: "C8", prize: 280 },
            { name: "C9", prize: 280, class: "disappear" },
            { name: "C10", prize: 280, class: "disappear" },
          ],
        },
      ],
    },
  ],
  // selected seats
  booking: [],
  // booked seats
  bookedSeat: [],
};

export default initialState;
